jobs:
  action:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Download Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./check/check

name: Test

on:
  schedule:
    - cron: "10 */6 * * *"
